[workspace]
resolver = "2"
members = ["iconoclast", "examples/demo/logic", "examples/demo/model", "examples/demo/repository", "examples/demo/uservice", "examples/demo/web", "examples/hexagonal/*"]

[patch.crates-io]
iconoclast = { path = "iconoclast" }
