port = 8080

database_url = "postgres://iconoclast:iconoclast@localhost/iconoclast"

[kafka]
# rdkafka-properties, see https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md#global-configuration-properties
"bootstrap.servers" = "localhost:9092"