# sample configuration as a starter to copy over to `config.toml` to create an environment-specific configuration
# the config.toml overrides the defaults from `config.default.toml`

database_url = "postgres://iconoclast:iconoclast@localhost/iconoclast"

[iconoclast]
port = 8080

[kafka]
# rdkafka-properties, see https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md#global-configuration-properties
"group.id" = "iconoclast-skeleton"
"auto.offset.reset" = "beginning"