# runt format-check, linting, compilation and tests
ci:
    cargo fmt --all -- --check
    cargo clippy -- -D warnings

    cargo check --all-targets --no-default-features
    cargo check --all-targets --all-features

    cargo nextest run --all-targets --all-features

    cargo clippy --all-targets -- -W clippy::pedantic

# build the OCI Image
docker:
    docker build .
