name: test
on: [ push, pull_request ]

jobs:
  test:
    name: test iconoclast
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest

      - name: install required native libs
        run: sudo apt-get install libsasl2-dev

      - run: cargo fmt --check

      - name: compile
        run: cargo check --all-targets

      - name: Run Tests
        run: cargo nextest run --all-targets

      - uses: crusty-pie/clippy@v1
        with:
          args: --all-features --all-targets

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
