version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - application
      - domain
      - errors
      - kafka
      - main
      - repository
      - web
    schedule:
      interval: daily

  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: "docker-compose"
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly