name: build

on:
  workflow_run:
    workflows:
      - test
    branches:
      - master
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      #      - name: Login to GitHub Container Registry
      #        uses: docker/login-action@v3
      #        with:
      #          registry: ghcr.io
      #          username: ${{ github.actor }}
      #          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get crate version from Cargo.toml
        id: cargo_version
        run: echo version=$(awk -F '"' '/^version =/ { print $2 }' Cargo.toml) >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=branch,suffix=-${{ github.run_number }}
            type=sha
            type=raw,value=${{ steps.cargo_version.outputs.version }}-alpha.${{ github.run_number }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          # push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
