name: Renovate
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: { }
  push:
    branches:
      - master
    paths:
      - .github/workflows/renovate.yaml
      - .github/renovate-global.json
      - .github/renovate.json5
      - "**/Cargo.toml"
      - "Cargo.toml"
      - "Cargo.lock"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.16
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          env-regex: "GITHUB_COM_TOKEN"
