name: test
on: [ push, pull_request ]

jobs:
  test:
    name: test iconoclast
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest

      - name: install required native libs
        run: sudo apt-get install libsasl2-dev

      - run: cargo fmt --check

      - name: compile iconoclast without any features
        run: cargo check -p iconoclast --all-targets --no-default-features

      - name: compile iconoclast with all features
        run: cargo check -p iconoclast --all-targets --all-features

      - name: compile demo
        run: cargo check -p uservice --all-targets --no-default-features

      - name: Run Tests
        run: cargo nextest run --all-features --all-targets

      - uses: crusty-pie/clippy@v1
        with:
          args: --all-features --all-targets

  skeleton:
    name: test skeleton
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo subcommands
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-override

      - name: install required native libs
        run: sudo apt-get install libsasl2-dev

      - run: cargo fmt --check
        working-directory: examples/skeleton

      - name: use iconoclast from source
        run: cargo override --path ../../iconoclast
        working-directory: examples/skeleton

      - name: compile skeleton
        run: cargo check --all-targets
        working-directory: examples/skeleton

      - name: restore manifest
        run: git restore examples/skeleton/Cargo.toml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: examples/skeleton
          cache-from: type=gha
          cache-to: type=gha,mode=max
